### PR TITLE
Replace backslashes in partial names with expected forward slashes

### PR DESCRIPTION
**Pull request by GRUBES**
When registering partials on a Windows machine, because partial names are derived using `path.join`, the names would contain backslashes, as mentioned in #78 

This quick fix ensures that there are never backslashes in the partial name, replacing them with the expected forward slashes. The path to the partial file itself is left untouched so that it remains cross-platform.

### CODE REVIEW

**Comment by GRUBES** [comment]
Working on an associated test, but it's a little strange since it would really only fail on Windows, never on *nix.

Also noted that the following tests fail on Windows because of line breaks:
* should not change file extension by default
* should change file extension when rename option is set to true
* should change file extension for nested files when rename option is set to true

**Comment by lewisbellwood** [comment]
Thanks for a great plugin. Just wanted to know when is this likely to be merged into the main branch as we are setting up a project that requires both mac and windows to work on this project.

**Comment by ismay** [comment]
@lewisbellwood 

I was thinking about how to do testing for windows as well as unix, but I'll do that later. This is a good fix in the meantime. Thanks @GRUBES

**Comment by lewisbellwood** [comment]
thanks @ismay for the fix. I had already patched my local version with fix. but will this be auto updated on npm?

**Comment by ismay** [comment]
@lewisbellwood np 👍 , yeah I just published it, so it should be installable now!

**Pull request merged**
