### PR TITLE
Adds check if paths are already absolute before joining the metalsmith path

### PR DESCRIPTION
**Pull request by zakhenry**

### CODE REVIEW

**Comment by zakhenry** [comment]
Hi @doodzik what is the reason for this closure?

**Comment by zakhenry** [comment]
@doodzik I'm not sure if you would like to reopen this PR or not as #98 was declined by @ismay

**Comment by doodzik** [comment]
Github shows me an error that this branch was "forced pushed or recreated" and I can't reopen it.
Can you submit it again?

**Comment by zakhenry** [comment]
Huh, yea I did a rebase. Will do

**Comment by zakhenry** [comment]
@doodzik created #99

**Pull request closed without merging**
