### PR TITLE
Fixes Tests. Adds default 'extension' option

### PR DESCRIPTION
**Pull request by afram**
Thought I'd fix the tests. Also added a default `extension` option. My use case for this is better compatibility for migrating jekyll sites over to metalsmith.

### CODE REVIEW

**Comment by ismay** [comment]
Cool thanks, I'll take a look at this asap!

**Comment by ismay** [comment]
Took a look at your PR. First of all, thanks for adding the tests. Second, I have a couple of questions:

* I don't think the changes to .gitignore are necessary. Did you commit that accidentally?
* What would be your reason for adding the `extension` option? I would like to stay as close as possible to the `metalsmith-templates` functionality and only diverge where absolutely necessary for doing what `metalsmith-layouts` is supposed to do. I assume you added it so you don't have to specify an extension in the front-matter?
* Also, correct me if I'm wrong, but the `setExtension` function does not seem to do anything (you're not returning a value and assigning it to `data` in the `Object.keys` scope.

**Comment by afram** [comment]
1. I use intellij. The intellij ignores are required for anyone who uses JetBrains software. `.pid` and `.seed` are probably not needed. I copied them out of a node gitignore template. `.log` is for all debug logs (npm-debug.log, etc). Finally `.DS_Store` is used my OS X to store folder metadata.

2. Yes, that is my reasoning for adding `extension`.

3. I opted for a function for 2 reasons.
  * It encapsulates the feature in a function
  * It gives that function a descriptive name, so there is less ambiguity around what is going on.
The setExtension actually checks whether `extension` is set, and then it updates the `data.layout` attribute for the current file. `file` is just a key in the `files` object.

**Comment by ismay** [comment]
1. The .gitignore for this project is only for this specific plugin. If you're going to use the plugin with metalsmith you can npm install it, and then use your own gitignore.
2. I don't think it's necessary to add the extension option for that reason. You can set it from the front-matter, which is more flexible, and doesn't diverge from metalsmith-templates.
3. I understand, but you're not returning a value and you're not assigning it anywhere. Right now it doesn't do anything of consequence. So for example:

```javascript
    function setExtension(file) {
      var data = files[file];
      if (extension) data.layout = data.layout + '.' + extension;
      // return the result
      return data.layout;
    }
    
    // assign it somewhere
    var foo = setExtension(file);
    // etc.
```

Hope that helps. So I'll close this. If you want to create a pull request for just the tests I'd be happy to take a look at it.

**Comment by afram** [comment]
I think you missed the point on this one. I use intellij to code. It creates a .idea folder (among other metadata). Opening this project to work on it means you need to exclude them else have them committed if not careful. As for .log - have you ever had NPM fail on you when working on a project?

Feel free to ignore this PR. You should be able to manage the tests on your own, right?

**Comment by ismay** [comment]
I understand that you use intellij to code, but this plugin isn't just 
for you. It doesn't make sense to include something that only relates to 
a particular environment in this project.

If you don't want to commit something, then just don't commit it.

**Comment by afram** [comment]
Look mate, this is going nowhere. I won't debate gitignore with you, but I have to say unfortunately you are incorrect on your last point.

files is an object.

```js
var files = {
'path/to/layout': { ...metadata... },
'anohter/path/to/layout': { ...metadata... }
}
```

`files` is available everywhere inside of the plugin function scope, because it is passed in as an argument.

`Object.keys(files)` returns an array of the keys in the `files` object. so `['path/to/layout', 'anohter/path/to/layout']`

With this in mind, when we pass `file` to `setExtension` we create a new scope inside of that function, where file is available. It doesn't really make a difference, but we could also point out that `file` is a String primitive, and so a copy is made to pass as an argument to `setExtension`. It's also worth noting that the `files` objet is available inside `setExtension` because it is declared within the plugin function.

Perhaps it also worth pointing out that the `files` object is passed around by reference, so we are always referencing the same `files` object.

OK, so with all this in mind, you will find that `files[file]` works just fine inside of `setExtension`. We also modify `file[file].layout` if needed.

Finally. All the tests pass, Including the new test I wrote that explicitly sets an extension.

Good luck with this.

**Comment by ismay** [comment]
> Look mate, this is going nowhere. I won't debate gitignore with you.

That's fine. I'm just explaining why I think it doesn't fit here, it's nothing personal. 

> but I have to say unfortunately you are incorrect on your last point.

I'm talking about `data.layout`, not the `files` object:

```javascript
    function setExtension(file) {
      // this instance of the data variable will only be available in setExtension
      var data = files[file];
      // so the assignment below doesn't affect the data variable in the parent function
      if (extension) data.layout = data.layout + '.' + extension;
      // unless you return it, and assign it
    }
```

A simplified example of my point: 

```javascript
var files = {
    one: 1,
    two: 2,
    three: 3
};

var example = function(files) {

    function setExtension(file) {
      var data = files[file];
      data = 10;
    }

    for (var file in files) {
      setExtension(file);
      var data = files[file];
      console.log(data); // will log 1,2,3 and not 10,10,10
    }

};

example(files);
```

Look at the `check` function for example. It has the same basic structure as your `setExtension` function, but it returns either `true` or `false`. Which makes it useful. Your function doesn't change anything, so it's useless. So please, if you're going to contribute to open source projects, don't take criticism too personal and be open to other people's suggestions.

**Comment by afram** [comment]
Um...

For your example you are correct, but that doesn't reflect what's going on. `files[file]` is an object, and objects are passed around by reference. That `data` variable you mention actually references an object, it's the same object that is later referenced.

example of objects passed around by reference.

```js
var a = {
    hello: 'world'
};

var b = a;
b.test = true;
a.test // true
```

An example of how metalsmith defines file metadata:

```js
var files = {
    'path/to/file': {
        layout: 'layout.hbs',
        someOtherMetadata: 'foo'    
    }
};

// Where file equals the key 'path/to/file'
var file = 'path/to/file';
var data = files[file];
// data now equals that object that contains a layout key.

// demonstrating in context

var example = function(files) {

    function setExtension(file) {
       // this is the same object that is referenced below
      var data = files[file];
      data.layout = 'something else';
    }

    for (var file in files) {
      setExtension(file);
       // this is the same object that is referenced above
      var data = files[file];
      console.log(data.layout); // will log 'something else'
    }

};

example(files);
```

I hope you can see it now :-)

**Comment by ismay** [comment]
My apologies, you're absolutely right! My mistake. Thanks for elaborating :).

**Pull request closed without merging**
