### PR TITLE
Partials support with path or object

### PR DESCRIPTION
**Pull request by rlamana**
Support for partials have been discussed before but here are the reasons why I think it should be a part of the ```metalsmith-layouts``` plugin:
* ```metalsmith-layouts``` sits on top of consolidate.js, and ```partials``` is now a main option in the consolidate engine.
* Larger projects might have a big amount of partial files, so registering them manually is not an option in this case. Support for a ```partials``` directory or pattern was needed. The whole partials directory should be read.
* consolidate.js treats the ```partials``` path relative to the ```layouts``` directory, therefore external plugins solutions to register the partials are not the best option. Internally, the path for each partial file found has to be calculated relative to the ```layouts``` directory. Also, developers might find this solution easier rather than installing a second plugin.

I hope my solution can help you guys!

### CODE REVIEW

**Comment by rlamana** [comment]
I might need to remove the test fix, and rebase from your latest changes

**Comment by ismay** [comment]
If I'm not mistaken any options unrecognised by metalsmith should be passed to consolidate. I haven't looked into `options.partials`, but wouldn't it be enough to use `options.partials` directly?

**Comment by rlamana** [comment]
@ismay you are right, however ```partials``` option in consolidate.js takes only a collection of ```{partialName: partialPath}``` elements. This helps to construct that object based on a given directory or pattern (very helpful for bigger projects with a lot of partials).

**Comment by ismay** [comment]
Ah right, I was hoping it would accept paths. I've always been doing the scanning for partials myself exactly because of this issue. So yeah, I agree, it sounds like a good idea to fix this here (and for metalsmith-in-place as well).

I haven't got the time right now, but I'll try to take a look at this tomorrow!

**Comment by rlamana** [comment]
@ismay great! review my PR, I'll be available to make any needed changes

**Comment by jmjf** [comment]
Would you consider generalizing this to support options.helpers?

Seems like that would be an additional value in settings[] and docs, renaming partials() to something more general (maybe dirOption()), and cloning to include helpers.

**Comment by rlamana** [comment]
Totally agree, it sounds like a good idea and a good design decision. I was also thinking that my solution was too specific for a particular kind of problem. Its more a 'helper' and that way the plugin can keep being a more generic interface on top of consolidate.js.

I'll make the changes as soon as I can and make a proposal.

**Comment by ismay** [comment]
I don't see why that would be a generalization. Isn't options.helpers only used by handlebars, whereas options.partials can be used by several engines?

**Comment by rlamana** [comment]
Ah, you meant to support handlerbars' helpers, sorry about that. What I had in mind was to avoid populating the ```options``` of your plugin with the specific options of just one (or more) template engine (in this case handlebars) and keep it more generic. 

However we can come up with an idea to support all these template engine specifics via something like 'helpers' of your plugin (that's what I thought you meant) without having to populate the ```options``` object with tons of stuff. The word 'helpers' might be confusing here though.

Anyway, that was just an idea... I can make the changes to my code to support handlerbars' helpers too, if you want.

I'm glad to help.

**Comment by jmjf** [comment]
Yes, my intent was to support the helpers option passed to consolidate.js so consolidate can register the helpers for Handlebars instead of listing the individual helpers in the options in Metalsmith--the same problem this is trying to solve for HBS partials.

Several templating engines support helpers. What I see in their source suggests they do not read all files in a directory. I'm not sure if they use an option.helpers (which consolidate would pass through).

I agree that loading up unneeded options is unwise. Maybe there's a way to build any additional options into an object that would be empty if not used and so wouldn't add any unnecessary options. That way, any "read all files matching pattern" options won't be on the stack if they aren't needed.

Unless you have concerns with the partials option, I vote for accepting the partials as-is and coming back to helpers and avoiding unnecessary options in a second PR.

**Comment by ismay** [comment]
@jmjf I see. I think it would be easier to deal with that in a separate issue or PR. We can continue the discussion there.

@rlamana Couple of questions: 
* What will happen if a directory contains non-template files? Maybe we should accept glob syntax (or an array of globs) to prevent trying to register files that aren't partials.
* Am I correct in assuming that only folders below `process.cwd()` can be accessed? That would be a nice fail-safe.

**Comment by jmjf** [comment]
Solution to the helpers problem.

Write a helpers module like:
```
module.exports = function () {
 	return({	
		'helper1': helper1,
		'helper2': helper2,
		...
		'helperN': helperN
	});
 };

var helper1 = function (parameters) {
     // code code code
};

var helper2 = function (parameters) {
     // code code code
};

...

var helperN = function (parameters) {
     // code code code
};
```
Alternatively, put each helper in it's own module and require each into the above module. Helper functions will be named by the key in the export. For example, the function assigned to the key 'helper1' will be called in templates as `{{helper1}}` even if the function it references is `someIncrediblyLongFunctionName`.

In build.js (assume above is `<projectDir>/layouts/helpers/getHbsHelpers.js`):
```
var getHbsHelpers = require('./layouts/helpers/getHbsHelpers.js');
...
var siteBuild = metalsmith(__dirname)
    .use(layouts({
        engine: "handlebars",
        partials: {
          // list of partials
        },
        helpers: getHbsHelpers()
    }
    .build(function (err) {
        if (err) {
            console.log(err);
        } else {
            console.log('Site build complete!');
        }
});
```
This takes advantage of consolidate's helpers parameter for Handlebars and requires no changes to metalsmith-layouts. It is also a better way to manage helper code, I suspect.

**Comment by ismay** [comment]
Or you could just register them directly on a handlebars instance (which will be picked up by consolidate), without passing any helpers to metalsmith. Handlebars is actually the easy one.

I still think it's a good idea to see whether we can figure out a good api for this, to make registering partials a little easier. Then, we might expand it to helpers. ping @rlamana

**Comment by rlamana** [comment]
I'm working on a possible solution for this. Sorry I haven't had much time to implement it yet.

IMHO it's a little bit 'trickier' than just all that. I agree with @ismay that a good api for this should be included as a basic implementation. Once we have that, we can think of other many possible 'use cases'. Based on my experience using it, these use cases are:

* Many users now use the metalsmith CLI config file, rather than coding. How would the 'helpers' be supported in this case?
* In a node environment, we'll probably have handlerbars' helpers installed via npm. Can we automatically use them without having to instantiate them or code anything?

Imagine I have the following ```metalsmith.json``` file (based on a real file of a project I'm working on):

```javascript
{
  "metadata": {},

  "source": "pages",
  "ignore": [""],

  "plugins": {
    "metalsmith-layouts": {
      "engine": "handlebars",
      "directory": "layouts/",
      "partials": "partials/",
      "helpers": [
        "handlebars-layouts", // An external npm helper package
        "./helpers/" // A directory where other helpers are
      ]
    },

    "metalsmith-markdown": {},

    "metalsmith-permalinks": {
      "pattern": ":title"
    }
  }
}
```

This should automatically register my listed helpers installed via npm, and add the ones I have coded for my project.

But to get there, we should first get to a good api, and then implement all these possible crazy ideas of mine :-D

I've created a more generic 'dirOption()' function based on my partials implementation like @ismay suggested, to help us fetch files relative to our 'layouts' dir and project dir. Let's start with that.

**Comment by jmjf** [comment]
I see your concerns about the wrapper module. For now, the wrapper module meets my needs, so I'm going with it until it doesn't. (If it ain't broke, don't fix it.)

I would definitely welcome an "import partials directory" option. So please get that working and in the code base. :+1: 

If by helpers installed via npm you mean some of the Handlebars helpers packages I see on npm, that may be a tall order. Different packages use different conventions. [Some](https://github.com/assemble/handlebars-helpers/blob/master/lib/helpers/helpers-i18n.js) export a register function, [though](https://github.com/SparkartGroupInc/handlebars-helper/blob/master/lib/index.js) not [all](https://github.com/cofounders/handlebars-helpers-pack/blob/master/helpers/date.js) with the same API. [Some](https://github.com/diy/handlebars-helpers/blob/master/lib/encodeURIComponent.js) export the helper directly. There are probably styles I didn't find with a quick search.

The API will need to resolve those differences or define a single approach and let people using the plugin wrapper the npm packages as needed. I'll be keeping an eye on this to see where it goes and will chime in if I have anything to contribute.

**Pull request closed without merging**
